### PR TITLE
Created EGLM

### PR DESCRIPTION
**Pull request by Carbon16**
This is my first addition to IVAO so sorry if I got anything wrong! :)

### CODE REVIEW

**Comment by Carbon16** [comment]
Sorry, I've just realised it looks like I've only uploaded the boundary- I'll add another commit with the runways etc. as soon as I can.

**Comment by Carbon16** [comment]
added additional polygons - ready for pull

**Comment by Crabcontrollerdave** [comment]
@Carbon16  Great work on this! il see if i can convert it sometime over the weekend for you

**Comment by Carbon16** [comment]
Thanks @Crabcontrollerdave . I was just wondering how else I could help the project? I assume just working through the to do list?

**Comment by Crabcontrollerdave** [comment]
@Carbon16 No worries! Helping out wherever you can is enough, thats what I do. Its totally up to you, you can go through the issues, or you can just do anything you feel like doing thats needed.

**Comment by moorer7** [comment]
I will merge and  correct but KML files should be in the KML folder, not the main directory

**Pull request merged**
