### PR TITLE
2408 - EGNM Tug Release Points

### PR DESCRIPTION
**Pull request by Brad1511**
- Tug Release points lines and labels added for Airac 2408
- #570 

image

### CODE REVIEW

**Comment by IslandControl** [comment]
Hey Brad, given the TRPs and the NPs are the same numerical value could you remove the NP values. Think it will tidy this up nicely.

**Comment by Brad1511** [comment]
Rgr will get this changed after work tonight.

**Comment by IslandControl** [comment]
No rush, thanks

**Comment by Brad1511** [comment]
image
Fixed

**Pull request merged**
