### PR TITLE
EGGP - POL4T SID Fix

### PR DESCRIPTION
**Pull request by Brad1511**
- Added POL32 to the procedure fix file so that the EGGP.sid file knows where it is.

image

### CODE REVIEW

**Comment by Brad1511** [comment]
#535

**Comment by Brad1511** [comment]
#536

**Comment by IslandControl** [comment]
Procedure turn (see ATC chat)

**Comment by Brad1511** [comment]
> Procedure turn (see ATC chat)
@IslandControl 
can this be merged and I will add Liverpool on the list of airports to add the curved lines on, but want to focus on the more commonly used airports first if that's okay

**Pull request merged**
