### PR TITLE
AIRAC 2202 Coordinate Changes + New Fixes

### PR DESCRIPTION
**Pull request by jakee2603**

### CODE REVIEW

**Comment by RadarController** [comment]
This looks good to me @jakee2603 so if you're happy to pull it out of draft I can approve and merge the PR. Thanks!

**Comment by jakee2603** [comment]
Hi Chris, 
I was looking at updating VALBO aswell, but seems to be already updated according to the AIP. But if you’re happy, I’ve took it out of draft.

**Comment by RadarController** [comment]
I can't see a change for VALBO either so that might have been a mistake in the airac update! I'll merge the PR now :)

**Comment by jakee2603** [comment]
I've just realised that I've missed a ; at the end of line 1385 for UDDIZ.

**Pull request merged**
